[build]
command = "npm ci --legacy-peer-deps && npm run build"
output_dir = "dist"

[build.environment]
NODE_VERSION = "18"
NPM_FLAGS = "--legacy-peer-deps"

[env.production]
name = "wilson-cv-architect" 